[[GAP_pkg_cohomolo]]
arch = "aarch64"
git-tree-sha1 = "9f3207e343ff984b4f0db78d72f93cd5f7bb61f2"
os = "macos"

    [[GAP_pkg_cohomolo.download]]
    sha256 = "86e5ae57fc0479cb8ed8ddcfcb891a7b9bf0792a47f340d0f68a653a17d6dd04"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cohomolo_jll.jl/releases/download/GAP_pkg_cohomolo-v100.600.1100+0/GAP_pkg_cohomolo.v100.600.1100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cohomolo]]
arch = "aarch64"
git-tree-sha1 = "ad182561ad172be5cb5b9ae5093f05d93b598bd3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cohomolo.download]]
    sha256 = "095c54813efa1c3f4f62f17ca135471fb59cb25c380c68b503b5a8c2a5bfbe0d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cohomolo_jll.jl/releases/download/GAP_pkg_cohomolo-v100.600.1100+0/GAP_pkg_cohomolo.v100.600.1100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cohomolo]]
arch = "aarch64"
git-tree-sha1 = "090f8c7bfd3d83b410acbff61ce6b31208d5982b"
libc = "musl"
os = "linux"

    [[GAP_pkg_cohomolo.download]]
    sha256 = "b81ba1c81d9e4344a425b4360820e4737ff6a071bad9fbef1a4ff122e1b7df3d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cohomolo_jll.jl/releases/download/GAP_pkg_cohomolo-v100.600.1100+0/GAP_pkg_cohomolo.v100.600.1100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cohomolo]]
arch = "aarch64"
git-tree-sha1 = "89704a4c8e216b4b6074a962a1818dd2891c6245"
os = "freebsd"

    [[GAP_pkg_cohomolo.download]]
    sha256 = "4dc3073e8bb38a946b258902bfb7d26536918cbf0a50450b4d4202bfb1f55526"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cohomolo_jll.jl/releases/download/GAP_pkg_cohomolo-v100.600.1100+0/GAP_pkg_cohomolo.v100.600.1100.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_cohomolo]]
arch = "powerpc64le"
git-tree-sha1 = "51664de6c7d54de15695f7f0d8f9bec1a52bbeca"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cohomolo.download]]
    sha256 = "54d62c18edcdaa0c41326cf409602c9bf10e1ff4152b4e850345df6d814557fe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cohomolo_jll.jl/releases/download/GAP_pkg_cohomolo-v100.600.1100+0/GAP_pkg_cohomolo.v100.600.1100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cohomolo]]
arch = "x86_64"
git-tree-sha1 = "6f671a68dbcaf5d7a0d0e2357c4fa4a3ab2cf186"
os = "macos"

    [[GAP_pkg_cohomolo.download]]
    sha256 = "3839463821233e05eeae12d265ac958bdbe48f7a03b9c9dee3e3302610852a63"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cohomolo_jll.jl/releases/download/GAP_pkg_cohomolo-v100.600.1100+0/GAP_pkg_cohomolo.v100.600.1100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cohomolo]]
arch = "x86_64"
git-tree-sha1 = "11d526646729fcc24f1aaaddfb963cb41cc4756d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cohomolo.download]]
    sha256 = "3225a107da8fc2b1b1e1a79d5c56c9baebdc0c66873b931fdbb680debd6efb73"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cohomolo_jll.jl/releases/download/GAP_pkg_cohomolo-v100.600.1100+0/GAP_pkg_cohomolo.v100.600.1100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cohomolo]]
arch = "x86_64"
git-tree-sha1 = "c139a8885f8c18b8fad0df3c044e1a3146063475"
libc = "musl"
os = "linux"

    [[GAP_pkg_cohomolo.download]]
    sha256 = "c974a45a327c834674464cba6c8ded0d5aab0df2fa3a16a18b88dab48c547fe6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cohomolo_jll.jl/releases/download/GAP_pkg_cohomolo-v100.600.1100+0/GAP_pkg_cohomolo.v100.600.1100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cohomolo]]
arch = "x86_64"
git-tree-sha1 = "76f8375d2180f094c7a66fb7bbfd84bac8ac5234"
os = "freebsd"

    [[GAP_pkg_cohomolo.download]]
    sha256 = "bc58dc47b804f57ae19b3d75abf93fb8654ba2900439106758a4443e0732ad31"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cohomolo_jll.jl/releases/download/GAP_pkg_cohomolo-v100.600.1100+0/GAP_pkg_cohomolo.v100.600.1100.x86_64-unknown-freebsd.tar.gz"
